### PR TITLE
Teking into account samples review comments

### PR DESCRIPTION
**Pull request by fmeheust**

### CODE REVIEW

**Comment by ejannett** [comment]
Are we not supposed to have copyrights in these files ?

**Comment by ejannett** [comment]
What about moving  tests in Junit test classes as opposed to within a "main" method ?

**Comment by fmeheust** [comment]
> Are we not supposed to have copyrights in these files ?

You are right, thank you!

**Comment by fmeheust** [comment]
> What about moving tests in Junit test classes as opposed to within a "main" method ?

They are not supposed to be tests but code samples.

**Comment by ejannett** [comment]
> > What about moving tests in Junit test classes as opposed to within a "main" method ?
> 
> They are not supposed to be tests but code samples.

OK,  So I think it is more natural and "clean" to have proper samples classes. 
you have ojdbc-provider-samples  sub project for this no ?

**Pull request merged**
